package rules;
dialect  "mvel"


 import models.*;

    dialect  "mvel"

    declare Location
        thing : String
        location : String
    end

    query isContainedIn( String x, String y )
        Location( x := thing, y := location)
        or
        ( Location(z := thing, y := location) and ?isContainedIn( x := x, z := y ) )
    end

    rule "go" salience 10
    when
        $s : String(  )
    then
        System.out.println( $s );
    end


    rule "go1"
    when
        String( this == "go1" )
        isContainedIn("Office", "House"; )
    then
        System.out.println( "office is in the house" );
    end

    rule "go2"
    when
        String( this == "go2" )
        isContainedIn("Draw", "House"; )
    then
        System.out.println( "Draw in the House" );
    end

    rule "go3"
    when
        String( this == "go3" )
        isContainedIn("Key", "Office"; )
    then
        System.out.println( "Key in the Office" );
    end


    rule "go4"
    when
        String( this == "go4" )
        isContainedIn(thing, "Office"; )
    then
        System.out.println( "thing " + thing + " is in the Office" );
    end

    rule "go5"
    when
        String( this == "go5" )
        isContainedIn(thing, location; )
    then
        System.out.println( "thing " + thing + " is in " + location );
    end
