import models.*;
import services.*;
dialect "mvel"

rule "Avoid2"
salience 2
when
    Entity (getValue( "TRAESUB1.VALUE") < 50  )

then
    System.out.println("cold");
end

rule "attack"
salience -1
when
    Entity (getValue( "PRESIDENT.ORDER") == true  )

then
    System.out.println("Attack");
end

rule "createpres"
salience 0
when
    Entity (getValue( "FIGHTERJET.ORDER") == true  )

then
    Entity e = EntityCollectionService.getInstance().getFromActions("PRESIDENT");
    System.out.println(e.toString());
    insert(e);
end

