import models.*;
import services.*;
dialect "mvel"

rule "Final"
salience 7
when 
    Entity (getValue( "HELICOPTER.FUEL") > 50  )

then 
    System.out.println("Dispatch"); 
end

rule "Abort"
salience -5
when 
    Entity (getValue( "WEATHER.STORM") == true  )

then 
    System.out.println("Abort"); 
end

rule "Weather_Station_Alert"
salience 2
when 
    Entity (getValue( "WEATHERSTATION.TRANSMITTING") == true  )

then 
    Entity e = EntityCollectionService.getInstance().getFromActions("WEATHER");
    insert(e); 
end

