package rules;
import models.*;
import services.*;

dialect  "mvel"
global boolean temp;
rule "Get Tortilla"
    salience 10
    when
       t1: Entity (getValue("TORTILLA.QUANTITY") > 1)
    then
        System.out.println("Tortilla Added to Order");
        boolean = true;
        //retract(t1);
end

rule "Add Beans" salience 9
  when
       Entity (getValue("BLACKBEANS.QUANTITY") > 1 )
  then
      System.out.print("Black Beans Added to order!\n");
      boolean = true;
end

rule "Add Cheese" salience 8
  when
      Entity (getValue("MOZZARELLACHEESE.QUANTITY") > 1 )
  then
      System.out.print("MOZZARELLACHEESE Added to Order\n");
      boolean = true;
end

rule "Add Chips" salience 7
  when
      Entity (getValue("CHIPS.QUANTITY") > 1 )
  then
      System.out.print("Chips Added to Order\n");
      boolean = true;
      if(temp == true){
      System.out.println("Burrito is Ready");
      }
end
