import models.*;
import services.*;
dialect "mvel"

rule "sr7"
salience 2
when
    Entity (getValue( "HELICOPTER.FUEL") >= 50  )

then
    System.out.println("dispatch_to_target");
end

rule "bad_weather"
salience 0
when
    Entity (getValue( "WEATHER.STORM") == true  )

then
    System.out.println("unsuitable_for_pick_up");
end

rule "update_weather"
salience 1
when
    Entity (getValue( "WEATHERSTATION.TRANSMITTING") == true  )

then
    Entity e = EntityCollectionService.getInstance().getFromActions("WEATHER");
    insert(e);
end

